import 'spare_part_models.dart';

final List<SparePart> sparePartMockData = [
  SparePart(
    id: 'SP-001',
    code: 'BRG-6205-2RS',
    name: 'بلبرینگ 6205',
    unit: 'عدد',
    quantity: 18,
    criticality: SparePartCriticality.high,
    minimumStock: 10,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-002',
    code: 'FLT-HYD-001',
    name: 'فیلتر هیدرولیک',
    unit: 'عدد',
    quantity: 4,
    criticality: SparePartCriticality.critical,
    minimumStock: 8,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-003',
    code: 'SEAL-IGM-01',
    name: 'کاسه‌نمد IGM2200',
    unit: 'عدد',
    quantity: 12,
    criticality: SparePartCriticality.medium,
    minimumStock: 6,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-004',
    code: 'FUSE-10A',
    name: 'فیوز 10 آمپر',
    unit: 'عدد',
    quantity: 35,
    criticality: SparePartCriticality.medium,
    minimumStock: 15,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-005',
    code: 'MTR-IGM-2200',
    name: 'موتور IGM2200',
    unit: 'دستگاه',
    quantity: 1,
    criticality: SparePartCriticality.critical,
    minimumStock: 2,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-006',
    code: 'BELT-CLB-03',
    name: 'تسمه CLABO',
    unit: 'عدد',
    quantity: 7,
    criticality: SparePartCriticality.high,
    minimumStock: 5,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-007',
    code: 'OIL-HYD-46',
    name: 'روغن هیدرولیک 46',
    unit: 'لیتر',
    quantity: 120,
    criticality: SparePartCriticality.low,
    minimumStock: 50,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
  SparePart(
    id: 'SP-008',
    code: 'PMP-GRF-07',
    name: 'پمپ گریس PUMP-07',
    unit: 'عدد',
    quantity: 2,
    criticality: SparePartCriticality.high,
    minimumStock: 3,
    unitPrice: 0,
    supplier: 'ثبت نشده',
    supplierPartCode: 'ثبت نشده',
    leadTimeDays: 0,
  ),
];

