import 'equipment_models.dart';

const List<Equipment> equipmentMockData = [
  Equipment(
    id: 'EQ-001',
    code: 'IGM2200-01',
    name: 'IGM2200',
    type: 'دستگاه کشش لوله',
    location: 'خط تولید 1',
    manufacturer: 'IGM',
    model: '2200',
    status: EquipmentStatus.operational,
    mtbf: 8200,
    mttr: 145,
  ),
  Equipment(
    id: 'EQ-002',
    code: 'CLABO-03',
    name: 'CLABO',
    type: 'دستگاه تولید لوله',
    location: 'خط تولید 1',
    manufacturer: 'CLABO',
    model: 'Tube Line',
    status: EquipmentStatus.maintenance,
    mtbf: 6100,
    mttr: 210,
  ),
  Equipment(
    id: 'EQ-003',
    code: 'IGM2200-02',
    name: 'IGM2200',
    type: 'دستگاه کشش لوله',
    location: 'خط تولید 2',
    manufacturer: 'IGM',
    model: '2200',
    status: EquipmentStatus.stopped,
    mtbf: 5400,
    mttr: 185,
  ),
  Equipment(
    id: 'EQ-004',
    code: 'PUMP-07',
    name: 'Pump 07',
    type: 'پمپ آب صنعتی',
    location: 'تأسیسات',
    manufacturer: 'Grundfos',
    model: 'Industrial Pump',
    status: EquipmentStatus.operational,
    mtbf: 12500,
    mttr: 95,
  ),
];
